### ISSUE TITLE
Información sobre la hora del reporte

### ISSUE THREAD

**Issue by LuccoJ** [TBMSP/ChileAlertaApi#1]
Creo que sería importante poder obtenir, junto con la hora UTC del evento, la hora exacta en que se ha publicado cada reporte. Esto ayudaría también a los utilizadores del API a aprender si, por ejemplo, es mejor utilizar el entry point ultimos_sismos_chile o ultimos_sismos&country=Chile desde el punto di vista de una actualización rapida.

**Comment by TBMSP** [comment]
Hola!
El parametro de los últimos sismos de Chile tiene un retraso máxima de 1
minuto desde que el CSN publico esa información, pero solo muestra los
últimos sismos (son 15 o 16), en cambio, "country=chile" tiene un retraso
de 2 minutos desde que el CSN o cualquier otra agencia sísmica publique su
información, de aquí se pueden obtener 100 resultados con referencias mas
"Generales" indicando localidades mas conocidas.
